### ISSUE TITLE
Make branch input boxes into dropdowns (or select elements)

### ISSUE THREAD

**Issue by jseppi** [cloud-gov/pages-core#1003]
It seems like we already have access to the list of branches in a repository (since they are listed in the "GitHub Branches" table). It would be a nicer user experience, I think, to have a dropdown box or `<select>` element for all the places where the user needs to specify a branch name instead of having to type it.

<img width="593" alt="screen shot 2017-06-13 at 1 29 02 pm" src="https://user-images.githubusercontent.com/697848/27098180-4a90ac6c-503c-11e7-88c5-6268b6e0e502.png">

**Comment by wslack** [comment]
Add that for adding a new site

**Comment by jseppi** [comment]
After #1027 is done, users will not be presented with a table of GitHub branches on the Site Settings page. That will maybe make it a little harder for them to fill out the `branch` and `demoBranch` text fields because they won't have a list of branches right in front of them. We might want to increase prioritization of this issue to make branch selection more user friendly.

**Comment by wslack** [comment]
I'm ok with this not being prioritized right now (unless it takes only an hour of work) given how rarely these settings are changed.

**Comment by wslack** [comment]
@el-mapache another possibility

**Comment by apburnes** [comment]
Closing for new round of UX research.
