### ISSUE TITLE
Run a link checker on generated sites

### ISSUE THREAD

**Issue by toolness** [cloud-gov/pages-core#1112]
In https://github.com/18F/pclob/pull/47 I added an optional link checker to a federalist site (PCLOB) that lets us know whether we have any broken links and such.

@wslack asked if this could be done for all federalist sites en masse and I said **YES** so I am filing this issue to declare my interest in assisting with its implementation at some point.

I don't think an initial integration should be that hard because the only dependencies are a few nodejs modules (chalk, express, simplecrawler, and cheerio). The checker could just run once the site is built, and users can look at the build log to see whether they have any broken links or pages that contain elements with duplicate `id`s.

Slightly better integration might allow for a configuration file in the repository to indicate whether Federalist should *only* deploy if no broken links are found. It could also define a list of pages in which broken links should be considered "warnings" rather than hard fails (we do this in the USWDS docs site for instance because some of its pages are pulling content via the GitHub API, and that content might contain broken links).

Even better integration might involve an actual view on the Federalist admin site that shows a nice HTML version of the checker's output, with switches to allow the "hard fail" functionality and exceptions to be configured via Web UI rather than config file.

**Comment by toolness** [comment]
Note also that the link checker does not visit each page in a headless browser, nor does it attempt to simulate one by e.g. running JavaScript on the page.  It just whizzes through the site's HTML files and takes a look at them, which is really fast. So we probably don't need to worry about this adding lots to Federalist's build time, though it might still be useful to provide some way for sites to completely opt-out of it if they really want to.

**Comment by wslack** [comment]
@toolness what are you thinking about this these days?

**Comment by toolness** [comment]
I think it'd be great to have as a feature!  I'm currently full-time on CALC though, so I don't have a ton of time to help with implementation.

**Comment by wslack** [comment]
Yep! Just wanted to make sure your thinking hadn't changed.

**Comment by apburnes** [comment]
Moving to https://github.com/cloud-gov/pages-core/issues/3943
