### ISSUE TITLE
Support Site, Demo, and Preview configuration settings for Hugo builds

### ISSUE THREAD

**Issue by thisisdano** [cloud-gov/pages-core#1219]
Federalist currently supports Site, Demo, and Preview configuration for its Jekyll builds. This configuration allows the user to 
> add additional configuration in yaml to be added to your `_config.yml` file when we build your site's [default|demo|preview] branch.

But this functionality isn't supported for Hugo builds. 

Hugo config files can be written in TOML, YAML, or JSON format as `config.toml`, `config.yml` or `config.json`. A complete solution to this issue would allow the environment config to be written in the format used by the Hugo configuration. An MVP solution might limit these settings to just one of these formats. We in DigitalGov use `YAML`, so that's the one we'd prefer 😉 .

This would allow Hugo users to set custom parameters for each environment, and lessen the need to write a custom plugin that uses Federalist's ENV vars. (Which would be useful, but it seems complex.)

I'd imagine the data entered in a custom configuration would look something like 
```
params:
  description: "Just another Federalist site."
  devmode: false
  env: master
```

_NB: params added via this method would need to include `config.yml`'s existing params since an appended `params` section would override the existing one._

**Comment by wslack** [comment]
Hi @thisisdano, you're correct and we didn't add this when experimentally enabling Hugo. Our team is not hugo experts so I'm curious what the right MVP would be.

**Comment by jseppi** [comment]
Related: https://github.com/18F/federalist-garden-build/issues/67

**Comment by wslack** [comment]
@el-mapache interested in this one?

**Comment by jseppi** [comment]
@thisisdano: How important of a feature is this for you all? I think your site is still the only one using `hugo`, and it seems like lacking the custom configs has not been much a blocker -- is that true?

**Comment by wslack** [comment]
Low priority given likely difficulty to implement.

**Comment by wslack** [comment]
https://github.com/18F/federalist-garden-build/issues/67 - closed this with similar ask as dup

**Comment by apburnes** [comment]
Stale
