### ISSUE TITLE
Add ability for users of the static site engine to specify a source directory (within their repo)

### ISSUE THREAD

**Issue by jseppi** [cloud-gov/pages-core#1346]
##### User Story

As a "static files" site admin on Federalist, I don't want Federalist vacuuming up my entire repo during the deploy process..

As an alternative to just uploading the entire repo content, users should be able to specify (in their site settings probably) a subdirectory to use instead.

Several sites, like fedramp-marketplace, perform this same kind of thing using jekyll (by specifying the `source:` option in their custom config blocks or `_config.yml` files).

**Comment by jseppi** [comment]
This will require modifications to both the main app the the build container.

Also, @jmhooper pointed out when he told me this idea, we should consider changing our site settings page a bit so that only relevant settings show up for the selected engine choice. Ie, the custom config boxes should not show up when the static engine is selected, but this new input box for the source directory should.

**Comment by wslack** [comment]
we should open an issue for hiding some of the settings. I don't think we'll prioritize that for now.

Re the general issue, it feels like something to put in backlog unless easy to do now.....what's the ROI do you think?

**Comment by jseppi** [comment]
It's not technically difficult but would touch a decent amount of code. I'd put it at the higher end of a medium lift.

It would result in faster builds for the sites that are currently using Jekyll as a workaround, because Jekyll and Ruby wouldn't need to be setup during those builds.  Fedramp Marketplace and I think USWDS are in this group.

**Comment by wslack** [comment]
But these sites could also just change their code to not sit in a subdirectory....hmm. Will ponder.

**Comment by jseppi** [comment]
It’s more for sites that have a custom node-based build.

**Comment by wslack** [comment]
I think this isn't a high priority for right now unless we see a lot of sites building like this.

**Comment by wslack** [comment]
(open to pushback)

**Comment by wslack** [comment]
How many sites would need this right now? USWDS and DOI?

**Comment by jseppi** [comment]
fedramp-marketplace also, I think.

**Comment by wslack** [comment]
This applies to many of our sites with wonky builds because they can't specify a source directory.

**Comment by apburnes** [comment]
Stale 🔮
