### ISSUE TITLE
Automatically prefix github url to existing repo form

### ISSUE THREAD

**Issue by el-mapache** [cloud-gov/pages-core#1366]
Rather than make the user type in the entire GitHub URL when filling out the `Add your own GitHub repository` form field, do one of the following things:

* Have the user type only `{username}/{repo-name}`
* Provide a dropdown of all the user's/their org's current repos that have allowed federalist, and let the user select one of those.

In both cases the user won't have to type the entire URL, which hopefully makes the form a little more seamless and potentially leaves less room for confusion/errors.

We may want to do a little further research into this as @jseppi noted that user may just be copy/pasting repos from the browser URL bar, which might lessen the need for this feature.

**Comment by jseppi** [comment]
Yeah, to add some context: there used to actually be two input fields here: one for the repo owner and one for the repo name. 

We changed it to take an entire github url instead because we thought users would typically just copy paste the full url from their browser address bar.

**Comment by wslack** [comment]
Gotten no complaints about the full URL, but a dropdown might be helpful. Setting to low.

**Comment by apburnes** [comment]
Stale
