### ISSUE TITLE
Show Add Site errors in the Add Site form when using a template

### ISSUE THREAD

**Issue by jseppi** [cloud-gov/pages-core#1395]
rather than showing errors at the top of the page (edited by @wslack)

ref: https://github.com/18F/federalist/pull/1394#issuecomment-352826172

**Comment by jseppi** [comment]
We would also need a place in the New Site From Template form(s) to show this error.

<img width="254" alt="screen shot 2017-12-20 at 4 46 34 pm" src="https://user-images.githubusercontent.com/697848/34232320-655c20cc-e5a5-11e7-8f0f-494c0af13a45.png">

**Comment by wslack** [comment]
Can we not put it at the top of the page?

**Comment by jseppi** [comment]
that interaction might not be great since the Add Site by Repo URL form is down below all the template blocks

**Comment by wslack** [comment]
Yeah; you'd have to send the user to the top of the page. I wonder what @maya would say about this - how do the USWDS suggest doing alerts inside of boxes like these?

**Comment by maya** [comment]
Can you describe what you're trying to do? Maybe provide what the error says and a screenshot of the page.

**Comment by wslack** [comment]
Error would be something like "you don't have access to this repo" or "you need admin access to the repo" or "you don't have permission to create the site" or "a repo already exists with that name"

<img width="1038" alt="screen shot 2017-12-21 at 2 35 18 pm" src="https://user-images.githubusercontent.com/10016577/34271896-36d95910-e65c-11e7-8735-21754bb3d5e6.png">

**Comment by maya** [comment]
Oh ok, well you can inline the error in the form as well as adding an alert at the top of the page.

**Comment by wslack** [comment]
Right. We're wondering about the best design for that, since the box is so small that a typical error box wouldn't work.

**Comment by line47** [comment]
I feel like the form that pops down after selecting `use this template` would work better if it could live in it's own space and not have to be squeezed in to be part of the 4 column template layout.

## Showing new site form on it's own
![screen shot 2017-12-22 at 4 51 15 pm](https://user-images.githubusercontent.com/1449852/34313339-6977ce06-e738-11e7-8c24-87bbd31f2943.png)

**Comment by jseppi** [comment]
Yeah, I think something like that would be a better interaction as well. We should also highlight the selected template "box."

**Comment by wslack** [comment]
Valid issue but I'm not sure we should prioritize. Putting in backlog.

**Comment by el-mapache** [comment]
The add site errors now display on this page, rather than redirecting. However, the UI could still be adjusted to show the error inline vs. the top of page.

**Comment by wslack** [comment]
edited top of issue to reflect this!

**Comment by apburnes** [comment]
Stale.
