### ISSUE TITLE
Process Content Review and turn into issues

### ISSUE THREAD

**Issue by wslack** [cloud-gov/pages-core#1493]
- Level of Effort: low
- Implementation Sketch (if higher than a "low" effort): open a bunch of :github: issues
- Definition of Done: issues are open for the document and the document can be archived
   - [ ] [Doc1](https://docs.google.com/document/d/1Du7VpBOWTybasIMXutQnWjzFTAfOS__wahc6_j5Xh9k/edit#heading=h.p4cckocgtmy0)
   - [ ] [Doc2](https://docs.google.com/document/d/10dl_3c6uTolRYtmMBhMJ7tnKVoXwvnAhTx93uLq2uSY/edit#)

Also sh

**Comment by annahsebok** [comment]
Before I start digging in on this, @leahbannon @OpenGlobe have y'all done any of this yet? I see a number of issues that have been opened since this one was, but want to be sure none of those are related to the content review findings so I can avoid duplicating issues. Thanks!

**Comment by davidewarren** [comment]
Time booked on 2/16 to for Will to walk through content docs - Open to team

**Comment by wslack** [comment]
We never got around to https://docs.google.com/document/d/1Du7VpBOWTybasIMXutQnWjzFTAfOS__wahc6_j5Xh9k/edit#heading=h.p4cckocgtmy0 so this is still outstanding.
