### ISSUE TITLE
Update signup form to align with visual changes to public pages

### ISSUE THREAD

**Issue by ericronne** [cloud-gov/pages-core#1565]
#### Description of feature or bug
Ready to go once #1563 is finished, provided we haven't obviated this form by that time!

#### Level of effort
Low. Only so much you can do with a Google form.

**Comment by ericronne** [comment]
@wslack do we intend to replace this form soon? If not, we can keep this open.

**Comment by wslack** [comment]
yes

**Comment by apburnes** [comment]
Stale
