### ISSUE TITLE
Remove publishedBranches.findOne code

### ISSUE THREAD

**Issue by el-mapache** [cloud-gov/pages-core#1677]
The `published-branch` controller and route definition file contains code for fetching a single published branch, something that we don't do in the code, aside from fetching files associated with the branch. Displaying metadata for a single published branch doesn't seem like it warrants it's own front-end view, and we don't have a need to consume it form the API currently, so I think it can be removed.

#### Definition of done

Unused code/tests removed for this endpoint

#### Level of effort - <low/medium/high>
*TBD*

#### Implementation outline (if higher than "low" effort):
*TBD*

**Comment by wslack** [comment]
this would be used to look up info about a specific branch (if we had a usecase?)

**Comment by wslack** [comment]
putting in icebox for now - a good thing to tackle, but seems less impact on its own?

**Comment by el-mapache** [comment]
Yep absolutely, just made this issue to surface it.

**Comment by wslack** [comment]
perfect!
