### ISSUE TITLE
EITI Case Study

### ISSUE THREAD

**Issue by jamiealbrecht** [cloud-gov/pages-core#1701]
#### Description of feature or bug

Write up case study of EITI. 

#### Definition of done

Two page EITI case study is written and edited. 

_After evaluating, edit this part:_

#### Level of effort - <low/medium/high>

medium

#### Implementation outline (if higher than "low" effort):

-check out examples
-talk to EITI team 
-write draft
-ask for feedback

**Comment by wslack** [comment]
Moved to ready. Example docs are here: https://drive.google.com/drive/u/1/folders/1aL078kZsA7DWF2CIutMSH7AYgvCVlkCK

**Comment by annahsebok** [comment]
We got a recommendation to nix long-form case studies. @wslack is still thinking about whether or not we want to kill this, but it's deprioritized for now.
