### ISSUE TITLE
Gather Federalist testimonials

### ISSUE THREAD

**Issue by annahsgraves** [cloud-gov/pages-core#1750]
#### Description of feature or bug

We've gotten a lot of great feedback from users about their experience with Federalist. We should gather all testimonials together so we can pull them for business development needs, speaking needs, or even to potentially add to the site.

#### Definition of done

We've reviewed our research documentation for testimonials and create a single document for them.

_After evaluating, edit this part:_

#### Level of effort - low

**Comment by annahsebok** [comment]
There are a lot of great quotes in [this research document](https://docs.google.com/document/d/1BHJpid-5Q2X1o3hM-Y2qLF1AjxDmnvvoJ9i2Z8r9zgU/edit) from late 2017, and I've grabbed some of the most salient ones for our [Federalist talking points](https://docs.google.com/document/d/1O_4zLgSlQDneaCu6qoh2lYdITa3wVSN3gWrbpn_QX20/edit#heading=h.tbaql8v70c80).

**Comment by annahsebok** [comment]
@wslack I've added this to `Backlog` but feel free to move it if you think it belongs elsewhere.

**Comment by wslack** [comment]
In general, totally ok to leave in "New Issues" for triage but suggest a place for it. I think this might be done with your work but can leave as-is for now.

**Comment by wslack** [comment]
Since you gathered these here: https://docs.google.com/document/d/1O_4zLgSlQDneaCu6qoh2lYdITa3wVSN3gWrbpn_QX20/edit#heading=h.tbaql8v70c80

Should we edit this issue to publishing a full testimonials document?

**Comment by annahsebok** [comment]
@wslack sorry, I'm not clear — that's my intent with this issue (thus the current Definition of Done). Is there something that's not clear there?

**Comment by wslack** [comment]
Ahhh got it, kk. Will leave this be then.

**Comment by apburnes** [comment]
Duplicate
