### ISSUE TITLE
Pull other action items from user research report

### ISSUE THREAD

**Issue by wslack** [cloud-gov/pages-core#1765]
#### Description of feature or bug

https://docs.google.com/document/d/1kYePO7bb28s4YGZRJVb7J4OLYmBck-ERjTWo9bfKb_M/edit#heading=h.45uaz3fzd94t has more due outs

#### Definition of done

we've added to the [action item document](https://docs.google.com/document/d/1mcUzYMQ7Op9fRKp-RvYOLVpiFmLOKghtaT4ljmnQlVc/edit)

_After evaluating, edit this part:_

#### Level of effort - low

**Comment by wslack** [comment]
There are other reports. @annahsebok to list.

**Comment by annahsebok** [comment]
The other reports I'm thinking of are the [fall 2017 research](https://docs.google.com/document/d/1BHJpid-5Q2X1o3hM-Y2qLF1AjxDmnvvoJ9i2Z8r9zgU/edit#heading=h.8y3d6ipwxte) and any of @ShannonBad's work from this current round of research she's in. Perhaps the 2017 research outputs have already been accounted for but I'm not sure.

**Comment by wslack** [comment]
I don't think there's anything else from the fall - this is specific to Shannon's first report, I think.

**Comment by apburnes** [comment]
🪓
