### ISSUE TITLE
Content is split correctly between Federalist sales site & Federalist user manual

### ISSUE THREAD

**Issue by annahsgraves** [cloud-gov/pages-core#1777]
#### Description of feature or bug

We need to differentiate what content belongs on the Federalist site (for sales) and what content belongs on the Federalist docs site (our how to guide). We started developing a new IA [here](https://app.mural.ly/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4) and need to continue to reorganize where content belongs based on the goals of each site. This is a result of the team discussion around the creation/voting for [an action plan](https://docs.google.com/document/d/1mcUzYMQ7Op9fRKp-RvYOLVpiFmLOKghtaT4ljmnQlVc/edit?usp=sharing).

#### Definition of done

- All existing content has been reorganized based on our IA and user testing.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Identify existing content for sales site
- [ ] Identify existing content for guide site
- [ ] Test (also outlined in #1723)
- [ ] Migrate content into new IA

**Comment by annahsebok** [comment]
Related to https://github.com/18F/federalist-docs/issues/212

**Comment by annahsebok** [comment]
Updated issue to reflect our new [content approach](https://docs.google.com/document/d/1V1RPQ3fFdclCDE2ZCm6Htt25DLcPLJ5mbE01UqnnvnI/edit#).

**Comment by annahsebok** [comment]
As #1723 is in progress, this epic is as well.
