### ISSUE TITLE
Iterate on the federalist-docs glossary

### ISSUE THREAD

**Issue by annahsgraves** [cloud-gov/pages-core#1799]
#### Description of feature or bug

We're creating a glossary in #1757, but it definitely doesn't include all of the terminology on the docs site that could benefit from being defined for less experienced users. We should add more.

#### Definition of done

The glossary includes definitions for additional technical terms on the federalist-docs.18f.gov site.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Review docs site for additional technical terms, making note of where existing and new glossary terms appear for wrapping
- [ ] Define them (they can be added to [our glossary doc](https://docs.google.com/document/d/1bXFrUgA6m5p_uuBigM7Fu-csVdjlL5NjywoMapQgvUw/edit))
- [ ] Review by @wslack
- [ ] Review by @jmhooper 
- [ ] Update existing JSON file to add new terms to site

**Comment by annahsebok** [comment]
Hi @el-mapache! I created this issue for future term definition and iteration. Do you want to add the text wrapping for existing+new terms here that you mentioned in standup earlier, or are you creating a separate issue for that?

**Comment by el-mapache** [comment]
I think probably a separate issue. That way, this work can be completed independently of the rest of the glossary implementation and won't be held up.

Question, as you review the docs, are you also going to note where the terms appear? Or is the implementor expected to do searches through the markdown files looking for the terms we want to define?

**Comment by annahsebok** [comment]
Makes sense to me @el-mapache! 

Re: noting where terms appear, it probably makes sense for that to be a part of this issue given that there's a review of the doc site happening here. I can add that to the implementation steps above. Thanks!

**Comment by annahsebok** [comment]
No worries at all @el-mapache! I think it makes more sense for it to happen over here. :)

**Comment by annahsebok** [comment]
Made a small edit — I suggest this work be on hold until https://github.com/18f/federalist-docs/issues/212 is completed (which will ultimately inform which additional words should be captured in the glossary).

**Comment by wslack** [comment]
👍 already ranked as such!

**Comment by apburnes** [comment]
🚫 🎲
