### ISSUE TITLE
Setup testing harness that allows us to do deep rendering

### ISSUE THREAD

**Issue by jmhooper** [cloud-gov/pages-core#1816]
#### User Story

As a developer, I would like to test how my components interact with each and the DOM, so that I can be confident the parts of Federalist's frontend interact together as expected.

#### Background (Optional)

Currently we only shallow render components to test them. We should consider [deep rendering](http://airbnb.io/enzyme/docs/api/mount.html) so that we can test how components work together instead of how components react with mocks.

#### Acceptance Criteria

- [ ] We have a test harness and a few high level tests that test the app top to bottom

#### Implementation outline (if higher than "low" effort):

- [ ] Setup JSDOM or similar to allow for deep rendering
- [ ] Write tests for important Federalist features that mock out interaction with the API, but not interaction with other components

**Comment by amirbey** [comment]
@jmhooper - can you please update this issue with details in accordancw with the new issues format ... thanks

**Comment by jmhooper** [comment]
@amirbey: Done

**Comment by apburnes** [comment]
Stale
