### ISSUE TITLE
Create a "Wardley Map" for Federalist

### ISSUE THREAD

**Issue by wslack** [cloud-gov/pages-core#1850]
#### User Story

As the Federalist buisness owner, a [Wardley Map](https://hiredthought.com/wardley-mapping/) will help me set a better product strategy by showing [trends and intent](https://goo.gl/images/cDoLCH).

#### Background (Optional)

- [Map Generator tool](https://hiredthought.com/wardley-map-chat-window/)
- [Example Map](https://hiredthought.com/wardley-map-chat-result/?map=%7B%22title%22%3A%22Your%20Map%22%2C%22elements%22%3A%5B%7B%22id%22%3A0%2C%22name%22%3A%22Content%20Manager%22%2C%22visibility%22%3A1%2C%22maturity%22%3A0.5%7D%2C%7B%22id%22%3A1%2C%22name%22%3A%22The%20ability%20to%20easily%20and%20quickly%20update%20content%22%2C%22visibility%22%3A0.9%2C%22maturity%22%3A0.5%7D%2C%7B%22id%22%3A2%2C%22name%22%3A%22Automatic%20builds%22%2C%22visibility%22%3A0.75%2C%22maturity%22%3A0.5416666666666666%7D%5D%2C%22links%22%3A%5B%7B%22start%22%3A0%2C%22end%22%3A1%7D%2C%7B%22start%22%3A1%2C%22end%22%3A2%7D%5D%7D)

#### Acceptance Criteria

- [ ] We've made a Wardley Map for Federalist

_After evaluating, edit this part:_

**Comment by bemosior** [comment]
Hello! You might also find [this article](https://realtimeboard.com/blog/wardley-maps-whiteboard-canvas/) useful (basics of mapping using RealtimeBoard, plus a few examples). Let me know if you'd like a hand.

**Comment by wslack** [comment]
@bemosior thank you! Alas, we can't just try out services like this without approval processes but I'm appreciative of the examples.

**Comment by apburnes** [comment]
Stale
