### ISSUE TITLE
Add pricing content and additional information to features page

### ISSUE THREAD

**Issue by annahsgraves** [cloud-gov/pages-core#1868]
#### User Story

As someone interested in Federalist, I'm curious about how much Federalist costs, what I can expect from the Federalist team, what's expected of me as a customer, a high-level understanding of how Federalist works, downloadable documents to share with stakeholders, and what I don't get. 

#### Background

When we conducted a card sort for #1723, we discovered that most users want to learn about Federalist features and pricing at the same time or within the same page experience, along with expectations, how Federalist works from a high-level, what isn't included, and access to downloadable documents. We should iterate on the Federalist features page (work completed in #1794) to add the items above. When it comes to pricing, we should be specific about outlining how much Federalist costs compares to the costs of other systems (not just to buy the product, but also how much it will cost to make sure that system is compliant and approved).

#### Acceptance Criteria

- [ ] Content has been added to the features page that outlines how much Federalist is and how that compares to other similar publisher prices (not just the product, but also how much it will cost to make sure that system is compliant and approved).
- [ ] Downloadables have been moved from the home page to the features page
- [ ] Content has been added to this page that covered expectations (of the Federalist team, of the customer, and what isn't included).
- [ ] High level visual diagram of Federalist has been added to page

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by annahsebok** [comment]
https://cloud.gov/pricing/ offers a few great examples for how we might outline pricing.

**Comment by annahsebok** [comment]
Small update - I made some changes to the original issue to make sure we're capturing all of the card sort findings (and not just pricing) that are documented for this page in [our IA](https://app.mural.co/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4).

**Comment by annahsebok** [comment]
Leaving implementation details for whoever is picking up this issue to assess and outline.
