### ISSUE TITLE
Federalist Wargames

### ISSUE THREAD

**Issue by wslack** [cloud-gov/pages-core#1874]
#### User Story

As a Federalist team member, I want to prethink some possible problem scenarios before they occur and how we should respond to them

#### Background (Optional)

During the OES downtime, there was no precedent on how to resolve and Will had to improvise.

#### Acceptance Criteria

- [ ] Devise some scenarios
- [ ] Talk them over and document results

_After evaluating, edit this part:_

**Comment by wslack** [comment]
Started work here: https://docs.google.com/document/d/1ieff6bzNswdMjt1jWkutMtHpV9vwkdkZjbLOxKojcBg/edit

**Comment by apburnes** [comment]
Stale
