### ISSUE TITLE
Create one pager for stakeholders on Federalist

### ISSUE THREAD

**Issue by wslack** [cloud-gov/pages-core#1912]
#### User Story

As a federal stakeholder, with interest in government websites, I would like to know about Federalist.

#### Background (Optional)

Some other groups in government are devoting a lot of attention to government website modernization. It would be helpful if they knew more about Federalist.

#### Acceptance Criteria

- [ ] A one pager is sent to GSA leadership for approval

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Survey existing material
- [ ] Draft new one-pagers

**Comment by apburnes** [comment]
Completed by the cloud.gov TTS leadership one-pager 2023 ⭐

**Comment by wslack** [comment]
@apburnes I love these 4.5 year old issues being closed!
