### ISSUE TITLE
Site branches pagination

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#1921]
#### User Story

As a user with with a federalist site containing > 30 branches, I should be able to see all 30+ branches in the sites branches page.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] When I visit the branches link in Federalist, I see either all 30+ branches displayed for a site or a link to few the "next" set of branches.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):
- [ ] Check code for Uploaded Files > View Files
- [ ] Add pagination to the API to allow fetching branches
- [ ] GitHubBranches React component to fetch all branches using pagination before render

**Comment by amirbey** [comment]
see sites -> uploaded files -> view files for an example of pagination buttons

**Comment by wslack** [comment]
This has been an issue for us in troubleshooting. People shouldn't have 30.

**Comment by apburnes** [comment]
We're building a wayback machine for each branch of each site instead.
