### ISSUE TITLE
Talking Points creation for others 

### ISSUE THREAD

**Issue by wslack** [cloud-gov/pages-core#1946]
#### User Story

As a GSA executive interested in spreading the word on Federalist, I need information that I can transmit to audiences I address.

#### Background (Optional)

Event 1: The event itself is focusing on how agencies and industry are leveraging open source as an innovation platform. 250 expected attendees will be a mix of federal IT leaders, managers, decision makers and influencers.

Event 2: a TED-style talk on building a foundation for ongoing innovation in the federal government and leadership on CIO engagement, digital government, and IT and identity infrastructure modernization. 2,000 attendees, including government leaders, market participants, regulators, policymakers, c-suite executives, financial institutions, and information technology firms.

#### Acceptance Criteria

- [ ] Draft big picture and the technical details in the [talking points doc](https://docs.google.com/document/d/1O_4zLgSlQDneaCu6qoh2lYdITa3wVSN3gWrbpn_QX20/edit#heading=h.sx367cr6bpux)
- [ ] Review from someone else on team. 
- [ ] Ship to DJ.

_After evaluating, edit this part:_

**Comment by apburnes** [comment]
Stale
