### ISSUE TITLE
Couldn't see my build without clearing my cache?

### ISSUE THREAD

**Issue by andrewmaier** [cloud-gov/pages-core#1962]
#### User Story

As a Federalist user, I'd like to see the homepage of the prototype I just created without having to clear my cookies/cache.

#### Background (Optional)

While prototyping the participation-lenses I initially published the site without including the `permalink: /` front matter. After publishing the site, I realized I had to add `/index.html` to see things. I added the front matter, but after refreshing the site I still couldn't see it. To do so I had to clear my browser cache (see photo).

![image 1](https://user-images.githubusercontent.com/2970/44689551-e6f30c00-aa25-11e8-87b0-9167cedc684b.png)

Repo: https://github.com/18F/participation-lenses
Branch: Master
The build was not failing, but for some reason I couldn't see the site at https://federalist-proxy.app.cloud.gov/site/18f/participation-lenses/

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by wslack** [comment]
Trying to figure out if we could have prevented this....

**Comment by wslack** [comment]
We set a default 404 object at the S3 level that redirects to /404/. This means that unless there’s custom behavior set up at the cloudfront level, all requests get redirected.

There's no custom behavior set up for people hitting the proxy, so the S3 bucket policy is used, and that means that requests for previews at https://federalist-proxy.app.cloud.gov/preview/gsa/fedsim_root/v3.0/ will fail over to https://federalist-proxy.app.cloud.gov/404/.

After the preview is built at https://federalist-proxy.app.cloud.gov/preview/gsa/fedsim_root/v3.0/, *the browser still served the cached redirect.* So now our users are stuck - and Andrew/Danielle have reported the same issue.

So I'm wondering how we can keep 404s working at the live URL level while not breaking them at the preview level
