### ISSUE TITLE
Develop integration tests which will allow for continuous deployment

### ISSUE THREAD

**Issue by eddietejeda** [cloud-gov/pages-core#2001]
#### User Story

<TODO>

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
NEVER @eddietejeda
