### ISSUE TITLE
How do we track UI errors? / Explore front-end error monitoring

### ISSUE THREAD

**Issue by eddietejeda** [cloud-gov/pages-core#2121]
#### User Story

In order to track UI errors, use the built-in events api to log any errors that occur in the UI.

#### Acceptance Criteria

- [ ] Create a general purpose error tracking endpoint in the api
- [ ] Log errors users experience in the UI and send then to the error tracking api endpoint
- [ ] Add a filter to the Admin UI for us to monitor the errors that occur

#### Implementation outline

- [ ] Create a specific API endpoint to log errors in the UI
- [ ] Add a listener in the UI frontend to log any errors that occur for a user
- [ ] Identify the user, the page, and the error associated the the UI error log

**Comment by apburnes** [comment]
Closing in favor of https://github.com/cloud-gov/pages-core/issues/4360
