### ISSUE TITLE
documentation providing guidance on high storage site repositories

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#2262]
#### User Story

A user with a large site (with lots of large assets) should have a sustainable and practical solution to storing large asset files (images, pdf, ppt, .docx) outside of their  site repo

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] Change made live via deploy of federalist.18f.gov

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] add documentation to instruct users to  create a repository  with their static assets only and add it as a site to Federalist with the static build engine and to follow the launch checklist for this new site

**Comment by apburnes** [comment]
No. Solving through new features.
