### ISSUE TITLE
Allow builds to be scheduled

### ISSUE THREAD

**Issue by melpers** [cloud-gov/pages-core#2305]
#### User Story

Allow builds to be scheduled at future dates & times.

#### Background (Optional)

Some stakeholders desire the ability to have content published and/or un-published at specific times (i.e. press releases, job postings, etc.) and to be able to have these changes queued up.

#### Acceptance Criteria

- [ ] allow user to enter cron formatted job in config but restrict frequency to that builds are not abused (ie: * * * * * --> every minute build)
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by eddietejeda** [comment]
@amirbey could this be implemented with a cronjob-like process that triggers builds?

**Comment by amirbey** [comment]
the builds are processed by SQS and SQS only allows delaying a build up to 15 minutes ... a potential solution could be when a cron job for when the the build is added to the SQS queue

**Comment by eddietejeda** [comment]
This pull request would addresses most of this issue:

https://github.com/18F/federalist/pull/2313

**Comment by amirbey** [comment]
yes it would as well ... #2313 is an MVP to address the immediate need to update pages daily (ie: expire upcoming events, ....)is there a strong need for execution at an exact time?

**Comment by melpers** [comment]
I think the ability to schedule a daily install at an approximate known time is a great option for most of our use cases. Any that need specific "At Exactly ??:00 O'Clock" scheduling can most likely be managed manually.

**Comment by amirbey** [comment]
can you share such scenarios that need builds at exact times as opposed to running nightly (ie: midnight)?

**Comment by melpers** [comment]
Our public affairs office has use cases where a press release needs to be coordinated with another organization's press release (i.e. NRL & NASA work on a joint project), or when some information in the release is embargoed until a specific date & time - perhaps when a paper referenced in the release is published publicly.

**Comment by amirbey** [comment]
@melpers -our builds are by branch. how does scheduling builds help for these instances?
From my current understanding, this sounds like a branch merging concern.

**Comment by melpers** [comment]
When using a CMS like Drupal (our current solution) you can create the page but leave it in an unpublished state with a set date & time to be become published. The first time the site bootstraps after that set date/time it will publish the page. It is also possible to schedule a page to be unpublished in the same fashion. HR uses this for job postings I believe. The scheduled pages do not impact the ability to update or publish other pages at real-time.

In this case where the site is re-built after a merge I'm not sure what options would be feasible - this is all new to me - but I don't think blocking builds would be a good solution.

I'm wondering if some hourly CRON could somehow check to see if there are any pages that need to be added or removed somehow and if so kick off a build. The build process itself would need to know to skip those pages if the date/time wasn't right as well, which I guess would just be part of the `createPages` definition (for Gatsby.)

**Comment by amirbey** [comment]
Publishing and unpublishing content is controlled by merging branches.  It sounds like you would want to schedule the merges on your GitHub repository.

On the other hand, from your suggestion re: CRON ... Yes, if the site was  built on a regularly scheduled interval your site could conditionally include/exclude pages.  That seems like a feasible option.

**Comment by apburnes** [comment]
Schedule with an GH action https://github.com/gr2m/merge-schedule-action
