### ISSUE TITLE
Netlify CMS: Inject configuration during Gatsby builds

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#2306]
#### User Story

A federalist user building a jekyll site opt to use Netlify CMS admin authenticated via Federalist to manage their content.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] federalist-build-container to set netlify configs for Gatsby sites during build process
- [ ] Change made live via deploy of federalist-build-container

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
@eddietejeda

**Comment by amirbey** [comment]
@eddietejeda

**Comment by amirbey** [comment]
https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/?origin_team=T025AQGAN

**Comment by davemcorwin** [comment]
Only injecting the configuration during build will prevent folks from authenticating during  local development which will make it difficult to actually configure Netlify CMS.

**Comment by davemcorwin** [comment]
Only injecting the configuration during build will prevent folks from authenticating during  local development which will make it difficult to actually configure Netlify CMS.

**Comment by apburnes** [comment]
Stale.
