### ISSUE TITLE
Create spec and validation logic for federalist.json

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-core#2416]
#### User Story

As a user I want immediate feedback if my `federalist.json` file is not formatted properly.

#### Background (Optional)

Currently, the Publish step of the build is the only consumer of this file, however, more consumers will likely be added as the the information that can be specified in the file grows. In addition, if the file is currently formatted incorrectly, an error will fail the build OR potentially have unintended effects.

We could surface this logic in multiple ways:
1. Run it as part of the build
2. Provide a check through the web app
3. Provide a check through a CL utility

#### Acceptance Criteria

- [ ] A json spec exists in Python and/or JS
- [ ] A file can be validated against the spec in Python and/or JS
- [ ] Made available via....<TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
Stale
