### ISSUE TITLE
add validation of the federalist.json file

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#2440]
#### User Story

A user's federalist.json file will be validated during the build process and will have feedback of failures.

#### Background (Optional)

Support existing federalist.json functionality let the user know if the the file is in accordance with the federalist.json schema and how to fix errors.

Note: this feature should be able to stand alone in a possible future library and not dependent on the federalist web app core to function

#### Acceptance Criteria

- [ ] validate the federalist.json once the build webhook is received
- [ ] if valid, queue the build if not valid then error the build and display appropriate error/logging messaging
- [ ] Change made live via deploy Federalist app

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
Rethinking the use of federalist.json
