### ISSUE TITLE
lambda@edge proxy proto

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#2452]
#### User Story

A user should be able to enable basic auth, set custom 404 for builds/site, and dynamic routing for s3 buckets

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [x] create repositories for lambda functions
- [x] create wildcard domain for cloudfront distro
- [x] explore redis vs dynamo vs s3
- [ ] SQS to pass data to datastore
- [ ] performance testing on cdn proxy

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
N/A
