### ISSUE TITLE
build url - copy to clipboard

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#2463]
#### User Story

A user can quickly share their builds with others using a copy to clipboard function

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] can click copy icon and be able to past the url
- [ ] Change made live via deploy of Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] add icon next to url to indicate copy to clipboard feature
- [ ] implement copy url

**Comment by davemcorwin** [comment]
![Screen Shot 2020-03-03 at 11.19.35 AM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/0da6e089-1d01-4327-9b71-42b4e7d34596)

**Comment by apburnes** [comment]
No longer valid.
