### ISSUE TITLE
Federalist dev environment provisioning

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#2533]
#### User Story

When a developer wants to test experimental features to cloud.gov, a script is available to setup and create a development environment to allow the developer to deploy directly to the dev space from the console to test experimental features.

#### Acceptance Criteria

- [ ] A script is available to provision and deploy cloud resources to setup a minimum viable environment to test different components of the federalist eco system
- [ ] After provisioning, a developer will be able to push changes directly the the dev environment 
- [ ] Possibly be able to teardown dev environment to save resources

**Comment by davemcorwin** [comment]
We are investigating using Terraform for this...

**Comment by apburnes** [comment]
NEVER

**Comment by apburnes** [comment]
Replaced by https://github.com/orgs/cloud-gov/projects/27/views/3
