### ISSUE TITLE
Prompt sole site owner to "delete" site if attempting to "remove" it

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-core#2542]
#### User Story

As a the only site owner, if I attempt to "remove" a site from the affordance on the "sites" page, I should be redirected to the Site Settings page | Advanced menu and informed about deleting the site.

#### Background (Optional)

Currently, if the user is the only owner of the site and attempts to "remove" it, they receive an unhelpful error.

![Screen Shot 2020-04-06 at 1.43.32 PM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/8acab839-ef92-4025-83f3-927046891ae8)

#### Acceptance Criteria

- [ ] update messaging to advise them delete the site in Site Settings along with site settings link
- [ ] Change made live via deploy Federalist

_After evaluating, edit this part:_

#### Implementation Detail
It may be helpful to know/display if the current user is an owner of the site.

cc @eddietejeda

**Comment by drewbo** [comment]
@apburnes can we remove this due to #3948?

**Comment by apburnes** [comment]
@drewbo sounds good to me. closed by #3954
