### ISSUE TITLE
builds stuck in queued blocking future commits from being built

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#2839]
#### User Story

<TODO>

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
has not occurred since 9/1 ... close if does not appear again within the next month ...?

**Comment by apburnes** [comment]
Closed by https://github.com/cloud-gov/pages-core/issues/4296
