### ISSUE TITLE
Site Setttings -> get rid of yaml config

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#2841]
#### User Story

<TODO>

#### Background (Optional)

We need to be able to announce this change to our users before implementing

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
No longer applicable.
