### ISSUE TITLE
Revisit dependabot configuration

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-core#2853]
#### User Story

The current dependabot workflow is time-consuming and noisy. Revisit the configuration for ALL our repos

#### Acceptance Criteria

- [ ] Dependabot raises security issues immediately
- [ ] Dependabot does not create PRs for dependency updates
- [ ] A monthly process runs for dependency updates via CircleCI/Github Actions
- [ ] Repeat for all repos
- [ ] Change made live via <TODO>.

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

Example similar GH Actions
https://github.com/Homebrew/homebrew-cask-fonts/blob/master/.github/workflows/google-fonts.yml

**Comment by apburnes** [comment]
Closed by https://github.com/cloud-gov/product/issues/2229
