### ISSUE TITLE
Lockdown

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-core#3064]
- [x] Restrict access to staging env to Federalist personnel
- [x] Restrict web bucket access to proxy servers
- [x] Implement caulking #3059 
- [ ] ?

## Staging env
We should discuss the impact of HOW we use the staging env as well. We probably shouldn't use it on any repo owned by a customer as that adds a webhook and status checks to the repo. We can fork repos and add them BUT this can have unintended consequences if their build interacts with 3rd party apis (though we would not have their secrets) It would be super nice to have our own Github org to manage all this and we may want to consider separate "Applications" or "orgs" in Github.

**Comment by drewbo** [comment]
Closed via https://github.com/cloud-gov/pages-core/pull/4027 and https://github.com/cloud-gov/cg-deploy-s3-broker/pull/47
