### ISSUE TITLE
when a user is deactivated, delete their associated sites/resources

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3087]
#### User Story

Only federalist users should have active sites on Federalist.

#### Background (Optional)

Users who are no longer on Federalist leave behind sites on Federalist which take up resources and should be removed after the user is no longer on the system.

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
N/A
