### ISSUE TITLE
add monitoring for bull queues (post SCR))

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3318]
#### User Story

Federalist admins can track how queues are being processed in the Federalist admin.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [x] Staging notify admin if a job stays on the queue for longer than x(ie: 60) seconds
- [ ] Production notify admin if a job stays on the queue for longer than x(ie: 60) seconds

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
No longer relevant.
