### ISSUE TITLE
setup staging pages application and sites domains

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3478]
#### Background (Optional)

Register wildcard domains needed for staging pages app and sites

#### Acceptance Criteria

Setup and ssl cert for following domains:
- [x] *.sites.pages-staging.cloud.gov
- [x] *.pages-staging.cloud.gov

#### Implementation outline (if higher than "low" effort):

- [x] https://github.com/cloud-gov/cg-provision/pull/855

**Comment by davemcorwin** [comment]
woohoo, special thanks to @bengerman13 for helping to get the staging urls up!!!!

**Comment by davemcorwin** [comment]
@amirbey Updated this to reflect staging only and created a new issue to track production: https://github.com/18F/federalist/issues/3516.
