### ISSUE TITLE
update GitHub oAuth apps for Pages rollout

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3604]
#### User Story

A federalist-user should be able to login to the Pages app.

#### Background (Optional)

Update federalist-users oAuth app 

#### Acceptance Criteria

Production app:
- [ ] update **Application name** from _federalist.18f.gov_ to _pages.cloud.gov_
- [ ] update **Homepage URL** from _https://federalistapp.18f.gov_ to _https://app.pages.cloud.gov_
- [ ] update **Authorization callback URL** from _https://federalistapp.18f.gov_ to _https://app.pages.cloud.gov_

Staging app:
- [ ] update **Application name** from _federalist-staging.18f.gov_ to _pages-staging.cloud.gov_
- [ ] update **Homepage URL** from _https://federalistapp-staging.18f.gov_ to _https://app.pages-staging.cloud.gov_
- [ ] update **Authorization callback URL** from _https://federalistapp-staging.18f.gov_ to _https://app.pages-staging.cloud.gov_

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
Completed
