### ISSUE TITLE
StatusPage for Pages

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3605]
#### User Story

A Pages user should have a StatusPage for Pages.

#### Background (Optional)

StatusPage.io update from federalist to cloud.gov pages

#### Acceptance Criteria

- [ ] create a StatusPage for Pages
- [ ] update StatusPage link on Pages app
- [ ] update StatusPage link on Pages marketing site
- [ ] Change made live via deploy Pages app
- [ ] Change made live via deploy Pages marketing site

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by drewbo** [comment]
Replacing with https://github.com/cloud-gov/product/issues/2182
