### ISSUE TITLE
Pages compliance memo revision (POST SCR) 

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3623]
#### Background (Optional)

Update the compliance memo to reflect Pages

#### Acceptance Criteria

- [x] updated by Pages Team
- [ ] reviewed by cloud.gov Compliance
- [ ] reviewed by cloud.gov Director
- [ ] update pages branch for pages site

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
https://docs.google.com/document/d/1hBqsYT2fGjAkcV_UjyBoHBRQJyou15DFHm7KHquWwfs/edit

**Comment by davemcorwin** [comment]
This is currently blocked pending feedback from stakeholders.

**Comment by davemcorwin** [comment]
@pburkholder @LindsayYoung Have y'all had a chance to review this?

https://docs.google.com/document/d/1hBqsYT2fGjAkcV_UjyBoHBRQJyou15DFHm7KHquWwfs/edit

**Comment by apburnes** [comment]
No longer applicable
