### ISSUE TITLE
Update env variables warning languge

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3660]
#### User Story

When adding environment variables, a Pages user should not be advised that the system is FISMA low

#### Background (Optional)

Pages will be FISMA moderate.
<img width="620" alt="Screen Shot 2021-10-12 at 4 56 41 PM" src="https://user-images.githubusercontent.com/1261794/137028214-aa78a28c-a096-4653-991c-e272c0723bca.png">

#### Acceptance Criteria

- [x] Reword message to take into account that Pages is a FISMA Moderate system
- [x] Change made live via deploy of Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by hursey013** [comment]
Resolved with https://github.com/cloud-gov/pages-core/pull/3972
