### ISSUE TITLE
remove "create from template" functionality. Have links to templates with instructions on how to use, should be same as any repo.

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3661]
#### User Story

A user should be able to create a new site from following instructions in the support docs.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] a new site based on the jekyll template can be created by following instructions
- [ ] a new site based on the gatsby template can be created by following instructions
- [ ] Change made live via deploy of Pages docs

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
scoped for SA

**Comment by apburnes** [comment]
Stale... but we get it.
