### ISSUE TITLE
Investigate running the entire system locally via docker (this is possible!!!)

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3662]
#### User Story

A Federalist developer can run all system components locally using Docker.

#### Background (Optional)

Currently, only the Federalist web app can be run locally.

#### Acceptance Criteria

- [ ] federalist-builder runs locally (using task pool) and interacts with REDIS queue and federalist endpoints
- [ ] federalist-garden-build posts logs to database and updates Federalist endpoints

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
Superseded by https://github.com/cloud-gov/pages-core/issues/4400
