### ISSUE TITLE
parse and analyze monthly netsparker reports (July 15)

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3680]
#### Background (Optional)

Monthly webscans report are manually processed and should be streamlined.  The webscan team now provides a json version of the report that can be parsed and summarized automagically.

#### Acceptance Criteria

- [x] script (Google app script) parses the reports folder and generates summary of actual findings
- [ ] includes information for all severities, CVEs
- [ ] compares against list of active Federalist sites

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] Google App Script parses reports folder

**Comment by davemcorwin** [comment]
Followed GSA instructions on renaming the file to avoid Cloudlock, but that also failed so I submitted the script for GSA approval.

**Comment by davemcorwin** [comment]
Sheet: https://docs.google.com/spreadsheets/d/1j4bJ_tbjBR-fprPmbka9g139bOXv8rNUZnZwO3Tn3c8/edit#gid=0
Script: https://script.google.com/home/projects/1o5rrhPJbnPulqX6grYX-6Ok6X78Ecmc1-kVbXQ_uAHzCCXHzWXu1yZSs/edit

**Comment by hursey013** [comment]
Received feedback from Sue, amended acceptance criteria to include additional requirements

**Comment by apburnes** [comment]
No longer applicable. Superseded by https://github.com/cloud-gov/pages-core/issues/4327
