### ISSUE TITLE
move queues configuration to config folder

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3681]
#### Background (Optional)
Bull Queues configurations should exist in a config file and not in the js codebase.
For example: https://github.com/18F/federalist/pull/3674/files#r736945269

#### Acceptance Criteria

- [ ] all queue config  are accessed from the config file directory
- [ ] queue configs no longer exist in the workers directory
- [ ] Change made live via Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] create queues config file (per queue?)
- [ ] queues should be initialized using config file

**Comment by apburnes** [comment]
It's a keeper.

**Comment by apburnes** [comment]
Completed by https://github.com/cloud-gov/pages-core/issues/4296
