### ISSUE TITLE
authorizers - remove federalist users admin

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3687]
#### User Story

<TODO>

#### Background (Optional)

Federalist users admin must be refactored to be in the pages-admin group.
For example, serializers.  It is possible that federalist users admin is removed altogether due to the existence of the admin interface.

#### Acceptance Criteria

- [ ] federalist-users admins can no longer access sites without site repo write access
- [ ] Change made live via Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] remove federalist-users-admin permissions from authorizers

**Comment by apburnes** [comment]
No longer applicable.
