### ISSUE TITLE
Add documentation on removing Federalist sites

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3714]
#### User Story

A user should know what steps to take to remove their site (production and development) from Federalist.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] write documentation on how an operator removes a site from Federalist
- [ ] Change made live via cloud-gov/cg-site

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by Ephraim-G** [comment]
Does any documentation currently exist pertaining to this issue?
