### ISSUE TITLE
FederalistUsersHelpers service relies on FEDERALIST_USERS_ADMIN env variable

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3718]
#### User Story

<TODO>

#### Background (Optional)

FederalistUsersHelpers service relies on FEDERALIST_USERS_ADMIN env variable.  This should dependency should be removed/re-evaluated.  _Note: The need for this service and associated scheduled jobs should go away when organizations are introduced in production._

#### Acceptance Criteria

- [ ] Removes FederalistUsersHelper functions

**Comment by apburnes** [comment]
Closed by https://github.com/cloud-gov/pages-core/pull/4131
