### ISSUE TITLE
Examine the workflow with changing the site's engine type.

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#3773]
The site engine type is a site wide value.  Would allowing users to define the site engine by branch be possible?

## Acceptance Criteria
- [ ] What is the lift to have branch level site engine and do the users need it?
- [ ] Does updating the site engine automatically kick off the main branch build? Should it automatically kick off a build on the production branch?

**Comment by davemcorwin** [comment]
This could be specified in the federalist.json file, we already read that for other info during the build, however, this would complicate the UI. I wonder if it woul dbe better to move toward "auto detecting" the engine UNLESS it is specified in federalist.json. This is complicated by old sites that use Jekyll but don't have a Gemfile.

**Comment by apburnes** [comment]
No Gemfile... Forgot about those sites.  Do we have a set or should we compile a set of site without the Gemfile?

**Comment by apburnes** [comment]
TOO FAR BEYOND ARE ABILITIES TO RATIONALIZE
