### ISSUE TITLE
Create a seed.js with required default data for every environment.

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-core#3811]
#### User Story

As an operator I want new environments to have required seed data.

#### Background (Optional)

We observed an error in the admin interface when creating an organization because the default `user` and `manager` roles did not exist.

#### Acceptance Criteria

- [ ] We can seed data in an environment with `yarn run seed`
- [ ] Change made live via deploy federalist.

#### Implementation outline (if higher than "low" effort):

- [ ] add file scripts/seed.js (ideally idempotent)
- [ ] add script `"seed": "node ./scripts/seed.js"`
- [ ] Create required `Role`s in the seed file 
- [ ] Remove `Role` creation from `create-dev-data`
- [ ] Update Readme where necessary

**Comment by apburnes** [comment]
Superseded by https://github.com/cloud-gov/pages-core/issues/4400
