### ISSUE TITLE
View domains for "deleted" sites in the admin interface

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-core#3825]
#### User Story

As a Federalist Operator, I want to be able to see ALL domains in the admin interface, even if the associated site has been soft deleted.

#### Background (Optional)

When investigating why a site with a custom domain was returning a 404, I could not see the domain in the admin interface because the query requires a site that has not been deleted.

#### Acceptance Criteria

- [ ] Domains page should display ALL domains and site information if present.
- [ ] Change made live via deploy of the admin interface.

**Comment by apburnes** [comment]
Rework issue to be able to see soft deleted resources in the admin UI

**Comment by apburnes** [comment]
No longer relevant.
