### ISSUE TITLE
Research how to handle custom domains and site deletions.

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#3828]
When a user deletes a site with custom domain/s associated to it, add functionality to delete the external domain service related to the custom domain/s

## Acceptance Criteria
- [ ] Research the workflow for deleting a site
- [ ] Do we add notices during the site delete process that the custom domains will be deleted?
- [ ] Do we make de-provisioning the custom domain required before a site can be deleted?

**Comment by davemcorwin** [comment]
We created https://github.com/18F/federalist/issues/3879 to prevent site deletion if there is a custom domain. I think this is OK for now and probably later when we push out custom domain management to users. I don't think it is a bad thing to force a user to explicitly remove the domain before removing the site. If y'all agree, can we close this issue?

**Comment by apburnes** [comment]
Closing for different workflow.
