### ISSUE TITLE
Create monthly concourse pipeline for security updates

### ISSUE THREAD

**Issue by hursey013** [cloud-gov/pages-core#3880]
Using the security alerts from Dependabot and CodeQL to fails future builds if left unresolved for longer than a month

- Investigate what alerts are available via the GitHub API
- Create pipeline to be run weekly, re-alerting using Slack, New Relic, or other means until issues are resolved

**Comment by apburnes** [comment]
Completed in https://github.com/cloud-gov/product/issues/2229
