### ISSUE TITLE
Remove SQS logic, dependencies, and config from pages-core

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#3915]
With the move to the Redis queue, we need to remove the AWS SQS related dependencies, configuration, and logic from the app and its deployments.

## Acceptance Criteria
* [x] Remove the user provided services supply now deprecated SQS credentials
* [x] Remove config for SQS
* [x] Remove logic within app for SQS

--- 

## Security considerations
Needed for SCR

**Comment by apburnes** [comment]
See https://github.com/cloud-gov/pages-core/pull/3928

**Comment by drewbo** [comment]
Deployed and services removed
