### ISSUE TITLE
Improve pages users authentication flow redirects

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#3923]
In order to properly redirect folks on UAA login/logout, We want to verify and add the proper redirect URI's to improve the authentication experience for pages users.

## Acceptance Criteria
* [x] Given a pages user is unauthenticated when the user logs in then they are redirected back to the home page for an authenticated user.
* [x] Given a pages user is authenticated when the user logs out then they are redirected back to the home page for an unauthenticated user.

--- 

## Security considerations
None

## Implementation sketch
- Verify which endpoint it best to authenticate against `uaa.<env>.cloud.gov` or `login.<env>.cloud.gov`
- The [logout docs](https://docs.cloudfoundry.org/api/uaa/version/75.23.0/index.html#logout-do) for UAA API
- Update logout url with proper redirect url param

**Comment by drewbo** [comment]
According to the platform team, `uaa.<env>.cloud.gov` or `login.<env>.cloud.gov` point to the same app (just different URIs) and can be used interchangeably. `login` is probably slightly nicer name from a user perspective

**Comment by hursey013** [comment]
Initial PR: https://github.com/cloud-gov/cg-deploy-cf/pull/701

Validated to be working as described by the acceptance criteria on latest platform production deployment.
