### ISSUE TITLE
Unable to remove user from Organization

### ISSUE THREAD

**Issue by Ephraim-G** [cloud-gov/pages-core#3936]
When a user is removed from an Organization a 404 is returned on the request delete/organization-role. 

## Acceptance Criteria

- [ ] Determine next steps and acceptance criteria

**Comment by drewbo** [comment]
I'm able to recreate this locally, it seems like the request body is parsed as `{}` because it's a `DELETE` method. It's worth investigating:
- whether this should instead be a `POST` so we can more easily pass data
- why the existing tests didn't catch this error
