### ISSUE TITLE
Disable checking of pages user status for external auth

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#3957]
Our external github auth endpoint checks for a user's cloud.gov Pages membership. This shouldn't be necessary for using Netlify CMS as a content editor as long as the user has access to the account. That check is currently performed by [Netlify CMS's auth code](https://github.com/netlify/netlify-cms/blob/dbf2920254fb3682e12463a6df8ded4b94b55be0/packages/netlify-cms-backend-github/src/implementation.tsx#L330-L333)

## Notes
- [Discussion](https://gsa-tts.slack.com/archives/G7EFTFW03/p1666034747701459)

## Acceptance Criteria

- [ ] Write up an ADR on how this could work
- [ ] Confirm that this authentication structure is acceptable per the current cloud.gov Pages SSP
- [ ] Users without a cloud.gov Pages account can use Netlify CMS to make content edits

**Comment by apburnes** [comment]
Closing stale.
