### ISSUE TITLE
Certain organization pages don't load

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#3968]
Shows `TypeError: Cannot read properties of null (reading 'email')` in the console

## Acceptance Criteria

- [ ] All organization pages load
- [ ] Test added to check for this specific failures

**Comment by drewbo** [comment]
The error occurs [here](https://github.com/cloud-gov/pages-core/blob/staging/frontend/components/organization/Edit.jsx#L107) when trying to sort an organization user without a UAA email. In theory that shouldn't really be possible so I'm wondering whether we should really update the UI to reflect a data model issue that we won't necessarily have in the future (post-migration)

**Comment by drewbo** [comment]
Cannot read properties of null (reading `id`) was also seen by another customer

**Comment by drewbo** [comment]
Both of these errors are the result of data model issues:
- User had their UAA email removed by an admin for debugging (causes the `TypeError...'email'` error)
- User was removed from the DB manually and then recreated but the `OrganizationRole` still existed (causes the `TypeError...'id'` error)

I'm inclined to close this for now and give ourselves better tools for managing the database without creating these errors

**Comment by apburnes** [comment]
@drewbo this seems to be an edge case. Your suggestion of additional admin tooling around user management is the best path to prevent us from creating these data errors when working directly with the db. Also, we should review the UAAIdentity and User schema's to make sure there are rules in place to not allow null emails or ids.
