### ISSUE TITLE
Create admin view for single organization

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#3976]
There is often a need for administrators to view information about an organization:
- Especially during the migration process
- Continuing during renewal/agreement discussions

Right now we have a list view `/organizations`, a sites list, a users list, and an edit view but no way to see all the summary information on one organization together.

## Acceptance Criteria

- [x] Create a pages at `/organizations/<org-id>` to display information about the org
- [x] It shows the org's attributes containing its name, agency, type, authorization, and status
- [x] It shows a list of the org sites
- [x] It shows a list of the org managers / users

**Comment by apburnes** [comment]
Added a few points to the acceptance criteria.
