### ISSUE TITLE
Add option to remove site from admin panel

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#3994]
Right now we don't have a way to stop building sites from the admin panel (they can only be removed directly by users)

## Acceptance Criteria

- [x] Add remove site button in the admin panel
- [x] Add confirmation step for removing sites
- [x] Add tests

**Comment by drewbo** [comment]
It looks like we had this functionality but then it was disabled and removed [here](https://github.com/cloud-gov/pages-core/commit/63fc91b316e883cb4b68a31350fc54832ee3f7b1#diff-27cf5046035d6b6cb4f6c5eb485f9cf8faf3b3064782b89b271cd044c051f7fdL10).

@apburnes do you have insight into why it was removed? I can reconnect and add back the verification step as well if needed

**Comment by apburnes** [comment]
I'm not sure why it was removed. It may have been due to site domains being controlled by command line at that point. Maybe we add controls to not be able to delete production sites without deleting the domain first.

**Comment by drewbo** [comment]
Sounds good. That should be covered since this ends up calling the same [`SiteDestroyer` function](https://github.com/cloud-gov/pages-core/blob/staging/api/services/SiteDestroyer.js#L33) which does check domain status
