### ISSUE TITLE
Add inline formatting to '[main]' entries in build logs

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4016]
Builds logs from the `[main]` logger are generally more important and should be formatted differently

## Acceptance Criteria

- [ ] Inline styling is added to main build log entries

**Comment by drewbo** [comment]
@apburnes @hursey013 @svenaas any thoughts on whether main logs should be bolder or less bold?
- Some of the main timing pieces are important, favoring more boldness
- The CPU/memory/disk stats also appear in the main logs and should be less important, potentially even hidden

**Comment by svenaas** [comment]
I haven't had to use these recently, of course, but I'm generally inclined to give the important stuff a little more visual importance so long as doing so won't interfere with grepping or similar filtering and searching
