### ISSUE TITLE
Add automation to site launch requests

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4031]
To help us streamline the site launch process, we want to add automation to steps in the launch to make it faster and more consistent for our team and customers.

## Notes

- This is a first step in the process and is exploratory on what is possible with our current tools. 
- Automate the creation of the site launch folder with a copy of the Site Review template.

## Acceptance Criteria

- [x] Create script.google.com project for cloud.gov Pages and share with team
- [x] Creates a new folder named the new Domain from the form entry ie “app.example.gov”
- [x] Copies the site review template doc into the created folder
- [x] Creates doc that can be used as a template email to send to customer and GSA IT

## Stretch or Future research possibilities
  - [x] Creates and sends two new Zendesk tickets, one for the customer confirming the site launch and another to GSA IT to scan the site
  - [x] When the new folder is created for a launch it notifies us in Slack

**Comment by Ephraim-G** [comment]
Pending cloudlock team review

**Comment by apburnes** [comment]
I think this is good to go. Awesome work @Ephraim-G . I'm going to close this out.

**Comment by Ephraim-G** [comment]
Sounds good and thank you for cleaning it up.
