### ISSUE TITLE
Flesh out the policies and actions needed for users (and their sites) that don’t migrate to UAA

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4035]
We need to codify the policy, tooling, and communications around _"deprecated"_ or non-migrated users and their sites so we can take action when we shutdown the authentication with Github.

## Acceptance Criteria
- [x] Write the policy and procedures around "deprecating" non-migrated users
- [x] Add tooling to deactivate the user and delete their sites
- [x] Publish a newspost, set a StatusPage, and email users about the policy

**Comment by apburnes** [comment]
@cloud-gov/pages-ops let me know what you think https://docs.google.com/document/d/1TCuA0YLRMF4_pg6HpvVwYOEo9pjgKwagWs1x8BplG2o/edit?usp=sharing

**Comment by apburnes** [comment]
@svenaas ☝ thoughts?

**Comment by svenaas** [comment]
@apburnes Very minor copyediting suggestions for consistency. Otherwise this looks good to me.

**Comment by apburnes** [comment]
https://github.com/cloud-gov/cg-site/pull/2244

**Comment by apburnes** [comment]
Closed by https://github.com/cloud-gov/cg-site/pull/2247
