### ISSUE TITLE
Send out notice for new Pages sites after GSA IT April 1 deadline

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4037]
As a customer, you need to be notified about the end of the GSA ATO and transition to the FedRAMP Authorization.

## Acceptance Criteria
- [x] Post the GSA IT policy
- [x] Write a brief transition guide
- [x] Publish a newspost
- [x]  Send email all pages users.

**Comment by apburnes** [comment]
@cloud-gov/pages-ops here's a [rough draft](https://docs.google.com/document/d/1dE5BYPGtMp89kG0fEzoQ71l0pZKzQgtxQNBfYNNP7Ck/edit?usp=sharing)

**Comment by apburnes** [comment]
@svenaas ☝ thoughts?

**Comment by svenaas** [comment]
@apburnes I've added copyediting suggestions in the draft.

**Comment by apburnes** [comment]
Current PR https://github.com/cloud-gov/cg-site/pull/2243

**Comment by apburnes** [comment]
Closed by [2246](https://github.com/cloud-gov/cg-site/pull/2246)
