### ISSUE TITLE
Test CISA Scanning Tool on Template Sites

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4057]
Sign up, use, and review the CISA site scanning program ([link to sign up](https://www.cisa.gov/free-cybersecurity-services-and-tools))

## Acceptance Criteria

- [x] Fill out their forms
- [X] Create an account with CISA
- [X] Setup the scanning for our template sites (https://uswds-11ty.pages.cloud.gov, https://uswds-gatsby.pages.cloud.gov, https://uswds-jekyll.pages.cloud.gov)
- ~Review the results~ Not able to scan our domains. Only IP addresses currently.

**Comment by Ephraim-G** [comment]
Update: we've made initial contact with CISA and have received the forms....forwarding to Rian and/or Ashley to fill out

**Comment by apburnes** [comment]
Sent forms

**Comment by apburnes** [comment]
Have we gotten any results back from CISA yet?

**Comment by Ephraim-G** [comment]
Nothing as of yet

**Comment by apburnes** [comment]
Closing since CISA Cyber Hygiene program does not currently scan domains and only IP addresses.
