### ISSUE TITLE
Notice to verify customer access to MAX.gov

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4060]
A customer need access access to MAX.gov to download the FedRAMP package, make sure customers know how to sign up and access the MAX.gov FedRAMP package and supply a checklist for getting access.

## Acceptance Criteria

- [x] Verify customers can access MAX.gov
- [X] Put together a ~checklist~ docs and notice for getting access to MAX.gov on cloud.gov
- ~Create a newspost about accessing it.~

**Comment by svenaas** [comment]
Max.gov process supports registration either by PIV/CAC or by email address. 

"Self-registration is available to Federal Government employees and contractors with a Federal Government email address. Federal employees/contractors with a non-government email address as well as non-federal employees performing Federal activities should contact [support* via phone or email]" ([source](https://portal.max.gov/portal/main/displayRegistrationForm)) — is it enough for us to know that our customers with government email addresses can get access, or do we need to know what's possible for contractors who don't have federal addresses?

*The service has support seven days a week (though not 24 hours a day). It has a 6-hour maintenance window early on Sunday mornings when it is unavailable.

**Comment by apburnes** [comment]
Putting this into our documentation with the links would be great. Add it to our [Customer Responsibilities](https://cloud.gov/pages/documentation/customer-responsibilities/) and link to it in the [Before You Launch](https://cloud.gov/pages/documentation/before-you-launch/). Also, I don't see a need for addressing contractors without government email addresses since Federal employees need to sign-off on their ATO docs and the majority of contractors have government email.

**Comment by svenaas** [comment]
Options: 

1. I could create a PR to merge just the MAX.gov account responsibility, and create an issue documenting the need to update these two pages more broadly (there may be one already), or
2. We could expand the scope of this task to include that work, though I think it would need input from more people.

**Comment by apburnes** [comment]
Just create a PR from your branch and maybe fix the language about needing a Github account to connect sites to pages. Then just link this issue in the PR.

**Comment by svenaas** [comment]
Done.

**Comment by svenaas** [comment]
Just merged the change to our customer responsibilities page. 

Personally I don't think we need a checklist of steps to get MAX.gov access — that process is documented by them, and will continue to be if it changes. I think we're better off linking to it.

As for the newspost, if we're going to do that I think we need some language explaining why customers need to be able to get the FEDRamp package, and the context around that. Is that already out there somewhere?

**Comment by apburnes** [comment]
Closed by https://github.com/cloud-gov/cg-site/pull/2268
