### ISSUE TITLE
Notify customers about upcoming Node 14 EOL

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4063]
Some sites build logs contain `WARNING: Node v14.x will reach end-of-life on 4-30-2023, at which point Pages will no longer support it.`. We should alert customers to this change so they can upgrade in advance.

## Acceptance Criteria

- [x] Agree on customer outreach content/method
- [x] Send out customer outreach

**Comment by drewbo** [comment]
I'd like to post to our status page and the next edition of the newsletter. We have similar language from a previous post:

> As part of our ongoing reliability and stability enhancements to cloud.gov Pages, use of node v14 will be deprecated as of April 30, 2023. Builds that specify an unsupported version in `.npmrc` will fail with the following messages in the build logs:

> Unsupported node major version `<some unsupported version>` specified in .nvmrc.
> Please upgrade to LTS major version 16 or 18, see https://nodejs.org/en/about/releases/ for details.

> In addition, the default node version, when one is not specified in `.npmrc`, will be v16.

> More information is available in our documentation at https://cloud.gov/pages/documentation/node-on-pages/.

> If you have any questions, please contact pages-support@cloud.gov.

I'll make a simultaneous change to cg-site so it reflects this: https://github.com/cloud-gov/cg-site/pull/2280

**Comment by apburnes** [comment]
@drewbo Looks good to me.

**Comment by drewbo** [comment]
- Website updated: https://cloud.gov/pages/documentation/node-on-pages/
- Incident: https://cloudgov.statuspage.io/incidents/npqvnv7myr8l
- Added to the upcoming newsletter
