### ISSUE TITLE
Review Slack Webhook URIs

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4068]
Our `Slacker` queue worker isn't posting failure messages: `error: Job Failed - Queue: 'slack' Job: '5|alert' "channel_not_found"`

I suspect that the slack webhook URIs provided via user-provided service credentials are tied to an old channel name (or maybe just the wrong channel name) thus not firing correctly. I'm working on getting access to the slack application with this info.

## Notes

- Slack Webhook Reference: https://api.slack.com/messaging/webhooks

## Acceptance Criteria

- [x] Get access to the Slack App
- [x] Add functional webhook URIs to staging and prod service credentials

**Comment by apburnes** [comment]
@drewbo should we close this out since we got the updated access tokens? Or do we want to change issue to be a runbook write up on procurement and implementation?

**Comment by drewbo** [comment]
@apburnes good call; I'll update this ticket and put it in the iteration

**Comment by drewbo** [comment]
The previous webhook was creatied using the legacy [incoming webhooks](https://api.slack.com/legacy/custom-integrations/messaging/webhooks) integration and also tied to a previous employees account which is why it started failing.

To recreate the webhook, I followed the new recommended way by [creating a slack app](https://api.slack.com/start/overview#apis), adding it to the TTS workspace, and adding a webhook. I'll track adding that information to a runbook in a separate ticket
