### ISSUE TITLE
Investigate completed builds without completed status

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4073]
Some builds run and complete but their `state` stays as "queued" or "tasked" (e.g. https://admin.pages.cloud.gov/builds/291054). This is an error on its own but also means the build logs aren't archived (because the build doesn't complete)

## Acceptance Criteria

- [ ] Investigate root cause
- [ ] Resolve ongoing bug
- [ ] Update DB to change old build states if necessary
- [ ] Remove and archive old build logs affected by this error

**Comment by apburnes** [comment]
Closing due to lack of recurring events.
