### ISSUE TITLE
Gather customer feedback on completing their own Pages ATO

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4103]
Collect feedback from customers going through their own agency ATO to understand their process and pain points.

Feedback Tracking Doc:
- https://docs.google.com/document/d/138Av0aTFXTFuYtUjaYhRyavR0Cp50EftdDkXoltzeKo/edit
- ATO process info survey https://docs.google.com/forms/d/e/1FAIpQLSeZiKKs6PnMEo-BiGc4wEBZ5st1YNmb4j0SqaX1iDhDokuQag/viewform

## Acceptance Criteria
- [x] Request FedRAMP PMO to for a list of completed/submitted cloud.gov pages ATOs
- [x] Create a list of questions and criteria we hope to learn from our customers.
- [x] Reach out to current non-GSA customers who have gone thru the ATO process

Wait till we receive response to do the following and theses tasks will be in a future issue.
- Schedule a meeting to get their feedback on the process
- Put together documentation that identifies pain points and common solutions/patterns

## Security Considerations
- Builds documentation to improve customer ATO process.

**Comment by Ephraim-G** [comment]
Constructed a pre ATO process survey to complement said documentation above and to gather data from our customers.

**Comment by Ephraim-G** [comment]
reached out to fedramp via email on getting a list of completed/submitted cloud.gov pages ATOs

**Comment by Ephraim-G** [comment]
@apburnes to confirm are all those customers listed in the doc confirmed to have already obtained their respective ATOs, in the process or a mix of both?

**Comment by Ephraim-G** [comment]
This is where FedRAMP support sent me https://marketplace.fedramp.gov/products/F1607067912

**Comment by Ephraim-G** [comment]
Received a zip file of all active cloud.gov ATOs , PMO did not have any new Pages ATOs to provide as of yet.

**Comment by apburnes** [comment]
Creat an ATO epic and add the survey in the reminder letter see #4200

**Comment by apburnes** [comment]
Closed by #4200
