### ISSUE TITLE
Add an admin view to see the number of production sites per org

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4118]
Allow our platform operators the ability to view and export our production sites per organization.

## Acceptance Criteria
- [x] Create admin api endpoints that returns a list of all productions with org, site, and domain info
- [x] Create a new admin page to view all orgs and their production sites
- [x] Enable filtering by organization, following the filter by org example at `/users/`
- [x] Calculate the number of production sites by getting all of the associated site domains per org
- [x] Add a simple CSV download 
- [x] Create a new Reports item in header nav and an initial Reports page where this new report will be the first one listed and linked.

## Security Considerations
none

**Comment by svenaas** [comment]
@apburnes The SQL is straightforward enough but I need to clarify the semantics of "**production** sites" in the first checkbox item above. Is it

1. All sites with a `site.domain`?
2. All sites with a `site.domain` and `active` = true?   
3. All sites with a `site.domain` and a `publishedAt` timestamp?
4. All sites with an associated `domain` record where `state` = ` provisioned`?

Or something even more specific?

**Comment by svenaas** [comment]
@apburnes What else would you like to see in this table?
<img width="1115" alt="image" src="https://github.com/cloud-gov/pages-core/assets/12150/d356a28f-8ad2-4e6e-917c-06099e5a61e3">

**Comment by apburnes** [comment]
I thinks that's a good start. 👍

**Comment by svenaas** [comment]
Note that the displayed count of sites is literally a count of Sites. Is this correct, or should it be a count of the associated Domains (such that a Site with two provisioned Domains counts as two published sites), or, going further, should it be a count of the potentially multiple domains listed in each provisioned Domain's `names`?

**Comment by svenaas** [comment]
Got the download button working, @apburnes. Do you want a demo of how this works at the moment?

Open questions:

1. Per my comment immediately above, am I calculating the number of sites the way you intended?
2. Where should the report page live in the admin client nav? So far I haven't linked it anywhere. 
3. There's one checkbox item up top that I haven't touched: "Create admin api endpoints that returns a list of all productions sites per org with org, site, and domain info". Does this mean just the production sites for a single org?

**Comment by svenaas** [comment]
We decided in demo today that there should be one result row per Domain, so a Site may show up several times if it has multiple domains associated with it. In addition to the query change it will make more sense for this to live on the Site controller instead of the Domain controller. Moving it is going to take a little unwinding and I want to get my in-process admin client changes (I'm working on the filterable table) to a commitable state first.
