### ISSUE TITLE
Launch multi-AZ application in cloud.gov staging for CP exercise

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/pages-core#4125]
To support the cloud.gov CP exercise, assume the role of a customer in api.fr-stage.cloud.gov that has a multi-instance application with multi-AZ data stores (at least RDS maybe also Elasticsearch).

## Acceptance Criteria

- [x] Demonstrate running app in fr-stage with health indicators for RDS.

**Comment by apburnes** [comment]
Follow up with compliance of the acceptance criteria and completion date.

**Comment by apburnes** [comment]
Launched app and documented in PR https://github.com/cloud-gov/internal-docs/pull/117
