### ISSUE TITLE
Monthly review of Org/Users in Zendesk

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4146]
Create a reccuring calendar invite and document to review our platform org and users with the corresponding Zendesk org/users.

## Acceptance Criteria
- [x] Create monthly meeting
- [x] Create a [doc](https://docs.google.com/document/d/1-ycE0A7GS5BFIU3KeHBcId6JktqYXl-XyIgYYpiZoQU/edit) to track meeting and org/user changes
- [ ] #4221

- This may be achievable via the Zendesk create_or_update_ many API by a cURL command or a small script in either python/java/ruby/Nodejs/Go seen [here](https://developer.zendesk.com/api-reference/ticketing/users/users/#create-or-update-many-users).

**Comment by svenaas** [comment]
I scheduled this meeting on the first Wednesday of the month, immediately preceding the existing ISSO touchpoint.

**Comment by Ephraim-G** [comment]
Got it, we're good to move forward on this.

**Comment by apburnes** [comment]
Let's update this issue's tasks after we hold the first recurring meeting this sprint.

**Comment by svenaas** [comment]
@drewbo I defer to you on whether we check off "Work through some possible scenarios to automate data pulls from the platform" above and move this to the next ticket or whether you want to make the next ticket a child of this one.

**Comment by drewbo** [comment]
let's leave this open, move this to the iteration matching the next monthly meeting, and then reasses then

**Comment by svenaas** [comment]
Next meeting is August 2 (though there is now an IR meeting scheduled across it) so I'll move this to 35.2.
