### ISSUE TITLE
Fix Concourse builds by specifying Node minor version

### ISSUE THREAD

**Issue by svenaas** [cloud-gov/pages-core#4152]
Concourse builds on #4145 were failing with 
```
node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
```
but were resolved by specifying Node image tag `18.15` instead of `18`. 

[This](https://github.com/nodejs/node/issues/43064) may be the underlying issue, as it evidently rears up with .Ubuntu 22.04 (credit to @drewbo for finding this).

## Acceptance Criteria
- [x] Node 18.15 specified
- [x] Concourse build succeeds

## Security Considerations
This change specifies a more specific minor version consistent with what was previously being used for builds. Instead of getting a newer minor version of Node 18 we are pinned to a specific minor version, which is an important detail, but not a problem at this time.

**Comment by drewbo** [comment]
Closed via https://github.com/cloud-gov/pages-core/pull/4151
