### ISSUE TITLE
Implement build task data model

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4184]
Implement the initial data model to support site build tasks.

See https://github.com/cloud-gov/internal-docs/blob/main/docs/ADRs/ADR-0013-pages-build-tasks.md for data model

## Acceptance Criteria

- [x] Create a `build_task` table.
- [x] Create a `build_task_type` table.
- [x] Create migrations to run against db when app is deployed

**Comment by drewbo** [comment]
Closed via #4245
