### ISSUE TITLE
ATO comms for Non-GSA customer's regarding the FedRAMP obligation

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4200]
Send out emails reminding our non-GSA customers about their obligation to send the FedRAMP PMO office the site ATO letters.

## Acceptance Criteria
- [x] Put together a reminder email
- [x] Send out the communications to our non-GSA customers
- ~Create a follow up comms plan.~ Wait to for responses before planning.

**Comment by Ephraim-G** [comment]
Reminder letter + survey https://docs.google.com/document/d/1dkT48PzVHkblkkvTX7NW3uVRLajMHNR3_8rhZGwW7XA/edit

**Comment by svenaas** [comment]
@drewbo @apburnes @Ephraim-G I raised one question and added some copy suggestions to [the reminder letter draft](https://docs.google.com/document/d/1dkT48PzVHkblkkvTX7NW3uVRLajMHNR3_8rhZGwW7XA/edit) that Ephraim prepared and linked above. Please have a look; we need to finalize that before sending comms.

**Comment by apburnes** [comment]
Waiting on final review from Cloud.gov leadership and should be ready to start shipping this week.

**Comment by svenaas** [comment]
Emails sent.
