### ISSUE TITLE
Some issues with modern-team-template

### ISSUE THREAD

**Issue by leahbannon** [cloud-gov/pages-core#427]
From UX study (medium priority):

All the participants experimented with the “show in menu” and “show in footer” check boxes. However, it seems like on the 3rd theme, there is no footer nav available. 
- Should users be able to create sub-pages in the pages list, when it’s not an option on the live site? 
- Also, within a theme, different “layouts” may allow side navs, and others don’t. There’s no indication of what’s possible, and where. 

Also Nav is hard to manage:

- https://github.com/18F/federalist-modern-team-template/blob/master/_data/navbar.yml
- https://github.com/18F/federalist-modern-team-template/blob/master/_layouts/sidenav-page.html
- https://github.com/18F/federalist-modern-team-template/blob/master/_config.yml
- https://github.com/18F/federalist-modern-team-template/blob/master/_navigation.json

**Comment by adborden** [comment]
FYI, I believe these are issues with https://github.com/18F/federalist-modern-team-template

They _might_ be fixed in https://github.com/18F/uswds-jekyll/tree/modern-team-template

**Comment by apburnes** [comment]
Stale
