### ISSUE TITLE
Rework invitation flow

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4305]
The user invitation flow has some bugs (#4108) and is generally a bit confusing for both org managers as well as admins. We should walk through the flow to see if there are ways it could be improved

## Notes

- Most recent prompt: https://gsa-tts.slack.com/archives/C04823NMA/p1700149255780659

## Acceptance Criteria

- [ ] Wait on #4108 
- [ ] Review on current documentation on inviting a user to an org and creating/inviting a user to a sandbox
- [ ] Map out current flow
- [ ] etc

**Comment by sknep** [comment]
I'd like to close this one out in favor of the Epic itself!  #4359
