### ISSUE TITLE
Soft-delete the legacy users who have never been associated with builds

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4311]
Soft delete legacy users who have never been associated to a build and have not migrated their account.

## Acceptance Criteria

- [x] Query all users that have not migrated their account, have no UAA Identity associated to it, and have never been associated to a site build
- [x] Soft delete the users

**Comment by svenaas** [comment]
The users in question are those from `user` 
```
where not exists (select id from uaa_identity where "userId" = "user".id) 
and not exists (select id from build where "user" = "user".id)
```

**Comment by svenaas** [comment]
[These](https://docs.google.com/spreadsheets/d/1DRKK5DZ-j_jGZGve2WgAm0SN-7OoR5tAIGXnuVVwBJo/edit?usp=sharing) are the users who will be soft deleted. @apburnes and @drewbo, please review before I soft delete them by setting `deletedAt` to `now()`.

**Comment by svenaas** [comment]
Users soft deleted in production.
