### ISSUE TITLE
Update the Pages 101 deck

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4312]
We want to update the Pages 101 deck with the latest features and metrics.

## Acceptance Criteria

- [x] Work with platform team to expand the Pages 101 deck to encompass platform features
- [x] Unify cloud.gov branding in deck
- [x] Review examples and showcase
- [x] Refine current features, pricing, and compliance info.

**Comment by sknep** [comment]
Ready for internal review, link sent in slack
