### ISSUE TITLE
Improve brittle admin user API test

### ISSUE THREAD

**Issue by svenaas** [cloud-gov/pages-core#4333]
Improve the Admin Users API with the hope of preventing an inconsistent failure.

## Notes

The Admin Users API test is inconsistently and infrequently failing in Concourse with 

```
  1) Admin - Users API
       GET /admin/reports/active-users.csv
         returns all users with UAA identities:
     AssertionError: expected [ …(2) ] to include '70,"user1@example.com","org-16|org-17…'
      at Context.<anonymous> (test/api/admin/requests/user.test.js:204:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I have not been able to reproduce locally, but hope to prevent this failure through improvement to the test.

## Acceptance Criteria

- [x] Test improved
- [ ] We experience a decent interval without this test failing unexpectedly

**Comment by svenaas** [comment]
I'm uncertain how long to wait before we consider a decent interval to have elapsed, check that second box, and mark this done and closed.

**Comment by svenaas** [comment]
Well, [_rats_](https://ci.fr.cloud.gov/teams/pages/pipelines/core/jobs/test-and-deploy-api-pages/builds/69?vars.deploy-env=%22staging%22).

The [job passed on re-run with the same inputs](https://ci.fr.cloud.gov/teams/pages/pipelines/core/jobs/test-and-deploy-api-pages/builds/69.1?vars.deploy-env=%22staging%22), so this still isn't deterministic.

**Comment by svenaas** [comment]
The test remains improved, but it also remains evidently flawed. I have not yet identified the problem.

**Comment by apburnes** [comment]
Closing since issue has not occurred.
