### ISSUE TITLE
UXR with some org managers about inviting new users

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4363]
## Acceptance Criteria

- [x] Create an interview guide
- [x] Recruit participants (In Progress)
- [x] Interview people
- [x] Synthesize results
- [ ] Create recommendations

**Comment by sknep** [comment]
Draft UXR Questions:
- What job-related task are you doing when you invite a user to your Pages organization?
  - If answer is something like "onboarding a new team member": Where are you in that onboarding flow?
- What job or task is the newly invited user doing or preparing to do?
- When inviting the user, are you in synchronous or asynchronous communication with the invited user?
- What training or support do you frequently provide to newly invited users?
- What organizational / contractual approvals related to user roles and membership happen externally to Pages, either before or after you invite them? (for example, do you wait until after a manager authorizes the new member to invite them? Do you add them to a GitHub org/team/repo before or after you invite the new user in Pages?)
- What do you expect to happen after you've submitted the invitation form on Pages?
- How soon after inviting the user do you expect them to log in?
- Compared to other tasks you do in Pages, how many (what percentage) of your visits involve user management (invitations, role changes, deleting users, etc)? When did you last invite a new user? 
- Under what circumstances do or would you add a user as an Org Manager _while_ inviting them to Pages?

**Comment by apburnes** [comment]
Would it be worth creating a google form to send out to our customers or do we want to be more selective with our interviewees and do it one on one?

**Comment by sknep** [comment]
I've asked Ephraim to identify potential interviewees based on his experience with support. I'm reaching out to them today. We may consider public recruiting, but we'd need to qualify them to make sure we get responses from different kinds of customers (large vs small org, internal vs external, content sites vs SPAs, etc)
