### ISSUE TITLE
Aggregate artifacts to support COE MOU on ATO Service

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4364]
Aggregate artifacts for COE MOU to support the ATO as a Service

## Acceptance Criteria

- [x] Add past docs and documentation
- [x] Create initial ATU template
- [x] Add current CRM and Packages
- [x] share wit COE's

**Comment by apburnes** [comment]
@kudehaatila is this done already?

**Comment by kudehaatila** [comment]
Pages compliance folder including current CRM and Packages shared with COE.
Working on the ATU template.

**Comment by kudehaatila** [comment]
@apburnes
See above comments.

**Comment by apburnes** [comment]
I think we are in a good place with the ATU template so I'm going to close this out.

**Comment by kudehaatila** [comment]
Yes, we are good to go. Thanks @Andrew Burnes - Q2AAAA
***@***.***>

Kudeha Atila (he/him) | PMP - CRISC, CISM, CDPSE - CompTIA Security+
Compliance Lead, cloud.gov Pages
Technology Transformation Services
U.S. General Services Administration
***@***.***
