### ISSUE TITLE
Meet about setting up guidance and implementation.

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4365]
Strategize and create action plan for ATO as a Service guidance and implementation.

## Acceptance Criteria
- [x] Set up time to meet with COE
- [x] Work with COE's on our how to cover our controls/CRM
```[tasklist]
### Tasks
```

**Comment by apburnes** [comment]
Blocked until MOU is signed

**Comment by kudehaatila** [comment]
@apburnes - Can we set up a time to meet with COE without the MOU in place?

**Comment by apburnes** [comment]
Email sent to setup a meeting.

**Comment by kudehaatila** [comment]
CoE provided draft MOU. Pages team reviewed and provided comments. Waiting for an updated MOU document from CoE.

**Comment by apburnes** [comment]
Still blocked on MOU

**Comment by apburnes** [comment]
MOU is signed

**Comment by apburnes** [comment]
Schedule meeting with CoE this sprint

**Comment by apburnes** [comment]
Met and reviewed documentation with CoE.
