### ISSUE TITLE
Add Pages shortcut to authenticated view on login.fr.cloud.gov

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4381]
Once a user is authenticated into cloud.gov, they see links to invite a user or go to the dashboard. To improve login for Pages users using the cloud.gov IDP, add a shortcut link to Pages. 

![Image](https://github.com/cloud-gov/pages-core/assets/4451344/23ecd175-6c1b-491d-ad7f-c3f280725d3c)

https://github.com/cloud-gov/cg-deploy-cf/blob/main/bosh/opsfiles/pages-clients-production.yml

## Acceptance Criteria
- [ ] Add Pages shortcut link

**Comment by svenaas** [comment]
For permissions reasons @markdboyd created cloud-gov/cg-deploy-cf#848 — @apburnes, could you please take a look at that?

**Comment by apburnes** [comment]
Approved. After it gets merged, it will deploy to dev and we'll need to test it.

**Comment by svenaas** [comment]
This is dev. What do you think? 
<img width="628" alt="image" src="https://github.com/cloud-gov/pages-core/assets/12150/69f6ffec-3778-4b3b-b214-30715d7b589f">

**Comment by svenaas** [comment]
(The link works; I did try it.)

**Comment by apburnes** [comment]
Follow up to identify where the env postfix originates. ie `Pages - Dev`

**Comment by markdboyd** [comment]
@apburnes 

https://github.com/cloud-gov/cg-deploy-cf/blob/main/bosh/opsfiles/pages-clients-dev.yml#L17
https://github.com/cloud-gov/cg-deploy-cf/blob/main/bosh/opsfiles/pages-clients-staging.yml#L17
https://github.com/cloud-gov/cg-deploy-cf/blob/main/bosh/opsfiles/pages-clients-production.yml#L17

**Comment by apburnes** [comment]
@markdboyd thanks!

**Comment by svenaas** [comment]
Yes, thanks @markdboyd — you beat me to it!

**Comment by svenaas** [comment]
And thanks, @apburnes, for cloud-gov/cg-deploy-cf#849

**Comment by svenaas** [comment]
As of this writing, dev looks like
![Image](https://github.com/cloud-gov/pages-core/assets/12150/9e53197e-944e-4b77-a670-e525d75a8df7)

and staging looks like
![Image](https://github.com/cloud-gov/pages-core/assets/12150/eb4b7fcc-3a60-4457-b0b1-4141d2faa09c)

🤨
