### ISSUE TITLE
Update pipelines to all use general-task and registry-image

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4394]
Update Pages pipelines to all use general-task and registry-image

## Acceptance Criteria
Update all pipelines in:
- [x] Core: https://github.com/cloud-gov/pages-core/pull/4392
- [x] Builder: https://github.com/cloud-gov/pages-builder/pull/572
- [x] Build Container: https://github.com/cloud-gov/pages-build-container/pull/457
- [x] Proxy: https://github.com/cloud-gov/pages-proxy/pull/205
- [x] Mailer: https://github.com/cloud-gov/pages-mailer/pull/37
- [x] Redirects: https://github.com/cloud-gov/pages-redirects/pull/241
- [x] GPG Keys: https://github.com/cloud-gov/pages-gpg-keys/pull/4
- [x] Build tasks: https://github.com/cloud-gov/pages-cf-build-tasks/pull/14

**Comment by drewbo** [comment]
Core: https://github.com/cloud-gov/pages-core/pull/4392

**Comment by apburnes** [comment]
Can we close this one out?
