### ISSUE TITLE
Identify metrics to monitor (& collection method/s) in order to determine feature usage/value to customers

### ISSUE THREAD

**Issue by sknep** [cloud-gov/pages-core#4405]
potential metrics:
- visits to `[siteID]/builds/[buildID]/scans`
- individually scan artifact (report) downloads
- relative time between build start date and report download
- relative time between build start date and view of the route at `[siteID]/builds/[buildID]/scans`
- How long it takes to run a scan and generate report
- Can a cost/scan be calculated

**Comment by apburnes** [comment]
N/A due to updated ASR views within the application.
