### ISSUE TITLE
Complete usability testing for build tasks/scans

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4409]
The usability testing for the build task user reach study.

## Acceptance Criteria
- [x] Write script
- [x] Schedule participants
- [x] Go through the feature together

**Comment by sknep** [comment]
Script here: https://docs.google.com/document/d/1bmE0wh3fYKAA93jZNgZemNsdk5Ojc6lQUydG-KgDiyQ/edit#heading=h.azandq2i9nvl
