### ISSUE TITLE
Draft customer communications about build tasks/scans (possibly note experimental feature, feedback welcome)

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4448]
Create draft copy for build tasks / build scans release.

## Acceptance Criteria

- [x] Put together rough outline of features
- [x] Send to TTS Outreach for their notes/edits

**Comment by sknep** [comment]
I think this is basically ready for TTS Outreach:

https://docs.google.com/document/d/18MoLoo-X-2rN--fZT28jZo4iF00PDcrQ-YegCLIEPx8/edit
