### ISSUE TITLE
Review and finalize the announcement email to inform customers about the website update and the availability of compliance documents.

### ISSUE THREAD

**Issue by KKAtila** [cloud-gov/pages-core#4470]
### Review and finalize

TTS Outreach Solutions team was not able to provide review feedback for this document. I plan to complete the review and finalize it. Once done, the document will be included in one of the upcoming newsletters.

**Comment by KKAtila** [comment]
Scheduled a meeting with Liz for July 2nd.

**Comment by KKAtila** [comment]
7/02: Met with Liz Camerlin and Kate Landis to present the docs that I have prepared to support the website updates.

**Comment by apburnes** [comment]
Close out for [#4469](https://github.com/cloud-gov/pages-core/issues/4469)

**Comment by KKAtila** [comment]
Re-open to review the doc in lieu of Office of Outreach doing it, and instead of sending email to customers, we will include the content of the document into one of our monthly newsletters.

**Comment by apburnes** [comment]
Add info for the monthly newsletter going out this week

**Comment by sknep** [comment]
I made some [edits here](https://docs.google.com/document/d/1plJTm9MSIbXUV4m1_C5WO_FPa1OXtX7Fv8Um-8Qv518/edit) and I think this is a great announcement for a stand-alone email. Something about ATO will probably get more opens than "monthly newsletter". I'm happy to help set this up in GovDelivery once Kelsey has had a chance to review it, and if Kudeha et al are ok with my edits
