### ISSUE TITLE
Allow people to suppress an ASR finding from within a report

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4600]
When a user is reviewing the site's automated site report, allow them to add/remove a finding in the report to the list of suppressed findings for their site.

## Acceptance Criteria
- [ ] ~Double check that we're suppressing everything we could be. A lot of reports right now still seem to have unsuppressed false positives.~ (separate issue)
- [ ] ~Could we write/provide documentation on a per-rule basis about what we suppress (or recommend suppressing) and why?~ (separate issue)
- [x] Create a POST request to the site's scan conf from a "suppress this finding" button on the report config settings
- [ ] ~Create an api endpoint to accept a POST request from the ASR to toggle a finding's suppression.~ (reused existing endpoint)

**Comment by drewbo** [comment]
Closed via #4623
