### ISSUE TITLE
Bug: investigate use of "latestBuildForBranch"

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4648]
There are a few issues with sorting (https://gsa-tts.slack.com/archives/C04823NMA/p1730214036769809) and displaying logs/links related to this function because many actions are predicated on having the latest build but some need the latest successful build for a branch.

## Acceptance Criteria

- [ ] Determine next steps and acceptance criteria

**Comment by apburnes** [comment]
Closed by #4663
