### ISSUE TITLE
Support for 301 redirects

### ISSUE THREAD

**Issue by gemfarmer** [cloud-gov/pages-core#755]
18F site would like to be able to redirect `18f.gsa.gov/feed/` to `18f.gsa.gov/feed.xml` (the current Jekyll standard) with a HTTP redirect instead of a meta-refresh. 

Why? Maintaining our audience as we migrate the site is important and not all devices will redirect RSS feeds with a meta-refresh. This will likely be important for many blogs using Federalist, so this update should be useful beyond this particular case. This is outlined in more detail in **[this issue](https://github.com/18F/18f.gsa.gov/issues/2260)**.

## Todo by 2022-01-20

- [ ] Have https://github.com/18f/pages-redirects repo be migrated to the cloud-gov org for Pages ownership.

**Comment by wslack** [comment]
Currently working to understand if Jekyll and support 301 redirects

**Comment by gemfarmer** [comment]
When I had looked before it didn't look like there was support, but this stackoverflow thread has me thinking that I _could_ actually solve this at the repo level after all

**Comment by jmhooper** [comment]
We may want to look here for setting up redirects: https://github.com/18F/federalist-docker-build/blob/master/publish.sh#L31-L35

Here's the docs for that S3 configuration: http://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html

**Comment by jseppi** [comment]
@lauraGgit brought up supporting redirects in the context of nicer URLs for single-page apps (so that an SPA doesn't have to use `#`-style addresses).

For reference, here's how Netlify allows users to specify custom redirects: https://www.netlify.com/docs/redirects/

**Comment by wslack** [comment]
Setting as medium as we could do it via config/custom file/etc.

**Comment by apburnes** [comment]
Proxy supports redirects in https://github.com/cloud-gov/pages-proxy/pull/176. Next steps are identify a possible pricing model to support managing site redirects.

**Comment by apburnes** [comment]
We will be migrating https://github.com/18f/pages-redirects into the cloud-gov GH org and begin the process of publishing the service offering.

**Comment by apburnes** [comment]
Current implementation is waiting on ATO

**Comment by apburnes** [comment]
Completed by https://github.com/cloud-gov/internal-docs/issues/148

**Comment by wslack** [comment]
Congrats @apburnes!!!!
